
tasks:
  - init: ./gradlew build


image:
    file: .gitpod.Dockerfile
vscode:
  extensions:
    - vmware.vscode-boot-dev-packintroduction/learn-gitpod/gitpod-yaml)
    - vscjava.vscode-java-pack# and commit this file to your remote git repository to share the goodness with others.
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
tasks:
  - init: ./gradlew build

image:
    file: .gitpod.Dockerfile
