spring:
#  jms:
#    template:
#      priority:
#      delivery-delay: 1000
#    pub-sub-domain: true
#    listener:
#      max-concurrency: 1

  artemis:
    mode: EMBEDDED
  cloud:
    gcp:
      project-id: my-rating-app-auth
  graphql:
    schema:
      inspection:
        enabled: true
    graphiql:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/my-rating-app-auth
  data:
    mongodb:
      database: my-rating-app
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}

server:
  port: 8080