spring:
  cloud:
    gcp:
      project-id: my-rating-app-auth
      credentials:
        location: classpath:my-rating-app-auth-firebase-adminsdk-uipee-b194862454.json
#      firestore:
#        project-id: my-rating-app-auth
#        credentials:
#          location: classpath:my-rating-app-auth-firebase-adminsdk-uipee-b194862454.json
  graphql:
    schema:
      inspection:
        enabled: true
    graphiql:
        enabled: true
  data:
    mongodb:
      database: myrating
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com