spring:
  jms:
    pub-sub-domain: true
  artemis:
    mode: EMBEDDED
  cloud:
    gcp:
      project-id: my-rating-app-auth
  graphql:
    schema:
      inspection:
        enabled: true
    graphiql:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
server:
  port: 8079